<?php

namespace IT\DynamicFormsBundle\Entity\Repository;

/**
 * FieldOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
