<?php

namespace IT\DynamicFormsBundle\Entity\Repository;

/**
 * FormResponseFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormResponseFieldRepository extends \Doctrine\ORM\EntityRepository
{
}
