<?php

namespace IT\DynamicFormsBundle\Entity\Repository;

/**
 * FormResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormResponseRepository extends \Doctrine\ORM\EntityRepository
{
}
