<?php

namespace IT\DynamicFormsBundle\Entity\Repository;

/**
 * FormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Returns a Form Entity by name
     *
     * @param $name
     *
     * @return mixed|null
     */
    public function getFormByName($name)
    {
        $qb = $this->createQueryBuilder('f')
            ->leftJoin('f.formFields', 'ff')
            ->leftJoin('ff.field', 'field')
            ->leftJoin('ff.fieldOptions', 'fo')

            ->select('f, ff, field, fo')

            ->andWhere('f.name = :form_name')
            ->setParameter('form_name', $name)
        ;

        $result = $qb->getQuery()->getResult();

        if (count($result) >0) {
            return current($result);
        }

        return null;
    }



}
